package com.shvmpk.url_shortener.dto;

import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShortUrlUpdateRequest {
    private String longUrl;
    private String alias;
    private Boolean isProtected;
    private Boolean isPasswordAutoGenerated;
    private String password;
    private String expiresAt;
    private Integer maxClicks;
}
